language: go

go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
- go get github.com/golang/dep/cmd/dep
- dep init

script:
  - ./test.sh

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
