name: build
on: [push, pull_request]
jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.13]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set GOBIN and add to PATH
        run: |
          go env -w GOBIN=$(go env GOPATH/bin)
          echo "::add-path::$(go env GOBIN)"

      - name: Lint and Test via ${{ matrix.goVer }}
        run: |
          go mod tidy -v && git diff --no-patch --exit-code
          go test -v -race -cover -timeout=20m -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... && bash <(curl -s https://codecov.io/bash)
      - name: Build on ${{ matrix.goVer }}
        run: go build ./...
